version: "3.8"

services:
  mongo:
    image: mongo:6
    container_name: dndnotes-mongo
    restart: unless-stopped
    ports:
      - "${MONGO_PORT:-27017}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-dnduser}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-dndpass}
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: dndnotes-backend
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      MONGO_URI: "mongodb://${MONGO_INITDB_ROOT_USERNAME:-dnduser}:${MONGO_INITDB_ROOT_PASSWORD:-dndpass}@mongo:27017"
      # Add other backend env vars as needed
    ports:
      - "${BACKEND_PORT:-8001}:8001"
    volumes:
      - ./backend:/app
    command: poetry run uvicorn main:app --reload --host 0.0.0.0 --port 8001

  frontend:
    build: ./frontend
    container_name: dndnotes-frontend
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      REACT_APP_BACKEND_URL: "http://localhost:${BACKEND_PORT:-8001}"
      # Add other frontend env vars as needed
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    volumes:
      - ./frontend:/app
    command: yarn start

volumes:
  mongo_data: